---
apiVersion: v1
kind: Service
metadata:
  name: exchange-rate
  labels:
    app: exchange-rate
spec:
  selector:
    app: exchange-rate
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
